env_name: mbpo_humanoid
num_train_steps: 5e6
eval_freq: 25000
# replay_buffer_capacity: 1e6

# Environment-specific overrides:
learn_temp:
  params:
    init_targ_entr: -2
    final_targ_entr: -2
    entr_decay_factor: 1.0

agent:
  params:
    horizon: 5
    warmup_steps: 10000
    dx_threshold: 0.015
