env_name: mbpo_cheetah
num_train_steps: 2e6
eval_freq: 25000

# Environment-specific overrides:
learn_temp:
  params:
    init_targ_entr: -1
    final_targ_entr: -16
    entr_decay_factor: 0.5

agent:
  params:
    horizon: 3
    warmup_steps: 10000
