env_name: mbpo_hopper
num_train_steps: 1e6
eval_freq: 25000

# Environment-specific overrides:
learn_temp:
  params:
    init_targ_entr: 0
    final_targ_entr: -2
    entr_decay_factor: 0.03125

agent:
  params:
    horizon: 5
    warmup_steps: 10000
