env_name: mbpo_ant
num_train_steps: 3e6
eval_freq: 25000

# Environment-specific overrides:
learn_temp:
  params:
    init_targ_entr: -2
    final_targ_entr: -16
    entr_decay_factor: 0.125

agent:
  params:
    horizon: 5
    warmup_steps: 10000
