env_name: mbpo_walker2d
num_train_steps: 2e6
eval_freq: 25000

# Environment-specific overrides:
learn_temp:
  params:
    init_targ_entr: -2
    final_targ_entr: -8
    entr_decay_factor: 0.0625

agent:
  params:
    horizon: 3
    warmup_steps: 10000
