env_name: mbpo_ant
num_train_steps: 2e6
eval_freq: 25000

# Environment-specific overrides:
learn_temp:
  params:
    init_targ_entr: 0
    final_targ_entr: -2
    entr_decay_factor: 4.0

agent:
  params:
    horizon: 3
    warmup_steps: 10000
