env_name: gym_ant
num_train_steps: 2e5
eval_freq: 10000

# Environment-specific overrides:
learn_temp:
  params:
    init_targ_entr: 1
    final_targ_entr: -3
    entr_decay_factor: 0.5

agent:
  params:
    horizon: 3
    warmup_steps: 10000
