# @package _global_
env_name: pets_cheetah
num_train_steps: 5e4
eval_freq: 10000

# Environment-specific overrides:
learn_temp:
  init_targ_entr: 0
  final_targ_entr: 0
  entr_decay_factor: 0

agent:
  horizon: 3
  warmup_steps: 10000
