# @package _global_
env_name: gym_ant
num_train_steps: 2e5
eval_freq: 10000

# TODO: Update all of these
# Environment-specific overrides:
learn_temp:
  init_targ_entr: 1
  final_targ_entr: -3
  entr_decay_factor: 0.5

agent:
  horizon: 3
  warmup_steps: 10000
