# @package _global_
env_name: gym_walker2d
num_train_steps: 2e5
eval_freq: 10000

# Environment-specific overrides:
learn_temp:
  init_targ_entr: -2
  final_targ_entr: -16
  entr_decay_factor: 0.015625

agent:
  horizon: 3
  warmup_steps: 10000
