defaults:
    - agent: sac_mve
    - env: mbpo_ant
    - hydra/launcher: submitit

experiment: test

# replay_buffer_capacity: max(${num_train_steps}, 1e6)
replay_buffer_capacity: ${num_train_steps}

num_seed_steps: 1000

renormalize: true
renormalize_freq: 1000

eval_freq: 10000
num_eval_episodes: 10
fixed_eval: true

device: cuda
action_repeat: 1

log_freq: 10000
log_save_tb: false

save_video: false
delete_replay_at_end: true

save_freq: 100000
save_latest: true
save_best_eval: true
save_zfill: 7

seed: 1

# For debugging:
num_initial_states: null # Use a subset of initial states
max_episode_steps: null # If set, use shorter episodes


hydra:
    name: ${env_name}
    run:
        dir: ./exp/local/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_${experiment}
    sweep:
        dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_${experiment}
        subdir: ${hydra.job.num}
    launcher:
        # Defaults: https://github.com/fairinternal/hydra-fair-plugins/blob/master/plugins/hydra-submitit/hydra_plugins/submitit/conf/hydra/launcher/submitit.yaml
        params:
            queue_parameters:
                slurm:
                    max_num_timeout: 100000
                    time: 4319
                    partition: learnfair
                    # partition: priority
                    # comment: For ICML

        mem_limit: 64
