pixels: True
latent_obs_dim: 64
frame_stack: 3

normalize_obs: False

obs_encoder_cfg:
  name: EncoderCNN
  class: agent.encoder.EncoderCNN
  params:
    frame_stack: ${frame_stack}
    latent_obs_dim: ${latent_obs_dim}

obs_decoder_cfg:
  name: DecoderCNN
  class: agent.decoder.DecoderCNN
  params:
    frame_stack: ${frame_stack}
    latent_obs_dim: ${latent_obs_dim}
