pixels: False
latent_obs_dim: 64

renormalize: False
renormalize_freq: 1000

obs_encoder_cfg:
  name: EncoderMLP
  class: common.utils.MLP
  params:
    input_dim: ${obs_dim}
    hidden_dim: 512
    output_dim: ${latent_obs_dim}
    hidden_depth: 2
    output_mod: tanh

obs_decoder_cfg:
  name: DecoderMLP
  class: common.utils.MLP
  params:
    input_dim: ${latent_obs_dim}
    hidden_dim: 512
    output_dim: ${obs_dim}
    hidden_depth: 2
