network:
  name: FCNet
  kwargs:
    hidden_width: 512
    hidden_depth: 4
    activation: swish
    init: trunc_normal
    batch_norm: False
  fit_params:
    batch_size: 256
    lr: 1e-3
    logvar_penalty_coeff: 1e-2
    wait_epochs: 4
    wait_tol: 1e-2
    early_stopping: True