reg_model:
  name: mle_soloist
  class: model_zoo.regression.MaxLikelihoodRegression
  params:
    input_dim: ???
    target_dim: ???
    model_class: ${network.name}
    model_kwargs: ${network.kwargs}
    mode: 'det'