reg_model:
  name: mle_ensemble
  class: mve.dx_models.MultistepDxEnsemble
  params:
    input_dim: ???
    target_dim: ???
    num_components: 7
    num_elites: 5
    model_class: ${network.name}
    model_kwargs: ${network.kwargs}
    mode: 'det'
    obs_dim: ???